version = 1

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/Watemlifts/active-directory-aspnetcore-webapp-openidconnect-v2"

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[transformers]]
name = "php-cs-fixer"
enabled = true

[[transformers]]
name = "autopep8"
enabled = true

[[transformers]]
name = "isort"
enabled = true

[[transformers]]
name = "standardrb"
enabled = true

[[transformers]]
name = "dotnet-format"
enabled = true